language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database Movie_Rental;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate
  - php artisan db:seed
  - php artisan key:generate

script:
  - vendor/bin/phpunit

addons:
  code_climate:
    repo_token: 12f8cd4dbac89897c959c6290aa67baa0a14469755e561ce2d46432fc2a8102a