language: php
php:
- 5.6

before_install:
- echo -e "Host 8t2.eu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_ad71df2bade9_key -iv $encrypted_ad71df2bade9_iv
  -in deploy_key.enc -out deploy_key -d

before_script:
- cp .env.travis .env
- mysql -e 'create database Movie_Rental;'
- composer self-update
- composer install --no-interaction
- php artisan migrate
- php artisan db:seed
- php artisan key:generate
script:
- vendor/bin/phpunit
after_script:
- vendor/bin/test-reporter

after_success:


addons:
  code_climate:
    repo_token: 12f8cd4dbac89897c959c6290aa67baa0a14469755e561ce2d46432fc2a8102a